### ISSUE TITLE
Use youtu.be to shorten messages

### ISSUE THREAD

**Issue by livingsilver94** [narwhalirc/tusk#1]
Currently NarwhalBot sends this when a Youtube URL is provided:
`<NarwhalBot> [ Title | Desktop: https://youtube.com/watch?v=ABC | Mobile: https://m.youtube.com/watch?v=ABC ]`
Given that a title may be pretty long, I think it's easier to the eyes to use the shorter Youtube URL like this `youtu.be/ABC`.

**Comment by JoshStrobl** [comment]
The URL shortened version doesn't support `m.` for mobile links. Example: `https://m.youtu.be/KmhdIU3RayI` isn't valid, because `m.` isn't a valid subdomain: https://dnschecker.org/#A/m.youtu.be
